const POSTS_REQUEST = "POSTS_REQUEST";
const POSTS_SUCCESS = "POSTS_SUCCESS";
const POSTS_FAIL = "POSTS_FAIL";
const POSTS_RESET = "POSTS_RESET";

const ADD_POST_REQUEST = "ADD_POST_REQUEST";
const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
const ADD_POST_FAIL = "ADD_POST_FAIL";

const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export {
  POSTS_REQUEST,
  POSTS_SUCCESS,
  POSTS_FAIL,
  POSTS_RESET,
  ADD_POST_FAIL,
  ADD_POST_REQUEST,
  ADD_POST_SUCCESS,
  DELETE_POST_FAIL,
  DELETE_POST_REQUEST,
  DELETE_POST_SUCCESS,
};
